version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
      - ./dataset:/app/dataset
    environment:
      - ENV=production

  streamlit_app:
    build: .
    command: ["streamlit", "run", "antivirus_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api
