name: HPC and Cloud Retraining Pipeline

on:
  push:
    paths:
      - 'data/raw/**'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: HPC Retraining
        run: |
          export PYTHONPATH=$PYTHON_PATH:$(pwd)
          python src/models/train.py

      - name: Upload Training Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: |
            models/model.pkl
            reports/

      - name: Check Model Improvement
        id: check_model
        run: |
          export PYTHONPATH=$PYTHON_PATH:$(pwd)
          python src/utils/model_check.py

      - name: Commit and Push changes
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add models/model.pkl reports/
          git commit -m "build: deploy improved model (recall threshold met)" || echo "No changes to commit"
          git push
